services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: amarvote_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Use Docker bridge gateway to reach host
      - SPRING_DATASOURCE_URL=jdbc:postgresql://172.17.0.1:5432/${DB_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_LIVERELOAD_ENABLED=true
      - RAG_SERVICE_URL=http://rag-service:5001
      - BLOCKCHAIN_SERVICE_URL=${VOTING_API_URL}
      - MASTER_KEY_PQ=${MASTER_KEY_PQ}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    volumes:
      - maven_repo:/root/.m2
    networks:
      - election_net
    depends_on:
      - rag-service

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: amarvote_frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      election_net:
        ipv4_address: 172.20.0.40
    depends_on:
      - backend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

  electionguard:
    build: ./Microservice
    container_name: electionguard_service
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      election_net:
        ipv4_address: 172.20.0.10
    environment:
      - FLASK_DEBUG=0
      - MASTER_KEY_PQ=${MASTER_KEY_PQ}

  rag-service:
    build: ./rag-service
    container_name: rag_service
    restart: unless-stopped
    ports:
      - "5001:5001"
    networks:
      election_net:
        ipv4_address: 172.20.0.50
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - RAG_SERVICE_PORT=5001
    volumes:
      - ./backend/src/main/resources/pdf:/app/data
      - rag_vectorstore:/app/vectorstore

volumes:
  maven_repo:
  rag_vectorstore:

networks:
  election_net:
    external: true
    name: amarvote_election_net